### PR TITLE
closes #2892 - Fix for Jira Collector requiring manual insert for Issue Type IDs

### LINKED ISSUE #2892: Jira Collector Needs to Auto Populate Issue IDs
Problem:

Currently the Jira collector forces the user to make a manual API call to look up the Issuetype Ids and then insert them into the properties file. Ideally the collector should handle this.

Solution:
Update the Jira collector to auto populate the issue type ids using the API `https://[your-jira-domain-name]/rest/api/2/issuetype`

### PR DESCRIPTION
**Pull request by Sbrenthughes**
Removes the requirement for the properties to use:
```
feature.jiraStoryIds[0]=
feature.jiraEpicId=
```

Now the collector only relies on `feature.jiraIssueTypeNames=` to have the issue type names in a comma separated string as usual.

### CODE REVIEW

File: collectors/feature/jira/src/main/java/com/capitalone/dashboard/collector/DefaultJiraClient.java [hunk 1]
```diff
@@ -385,6 +420,13 @@ private static String getIssueType(JSONObject issueJson) {
         return getString(issueType, "id");
     }
 
+    /**
+     *  Returns issue types from settings or default values if settings don't exist
+     * @return issue type id string
+     */
+    private String getIssueTypes(){
+        return featureSettings.getJiraIssueTypeNames() == null ? DEFAULT_ISSUE_TYPES : String.join(",", featureSettings.getJiraIssueTypeNames());
```
Comment (rvema) [inline collectors/feature/jira/src/main/java/com/capitalone/dashboard/collector/DefaultJiraClient.java]: May be you could use ArrayUtils.isEmpty()

Comment (rvema) [reply collectors/feature/jira/src/main/java/com/capitalone/dashboard/collector/DefaultJiraClient.java]: ArrayUtils.isEmpty(featureSettings.getJiraIssueTypeNames())
